"use client";

import { Suspense, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import type { DeepDive } from "@/lib/ai";

function TodayContent() {
  const params = useSearchParams();
  const id = params.get("id");
  const [dive, setDive] = useState<DeepDive | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    setLoading(true);
    setError(null);
    const url = id ? `/api/ai/deep-dive?id=${encodeURIComponent(id)}` : "/api/ai/deep-dive";
    fetch(url)
      .then((r) => r.json())
      .then((d) => {
        if (d.error) throw new Error(d.error);
        setDive(d.deepDive);
      })
      .catch((e) => setError(e.message))
      .finally(() => setLoading(false));
  }, [id]);

  return (
    <div className="pt-24 pb-16 px-6">
      <div className="max-w-3xl mx-auto">
        <div className="mb-8">
          <p className="text-neon text-xs font-semibold uppercase tracking-widest mb-2">
            {id ? "Deep dive" : "App of the day"}
          </p>
          {!id && (
            <p className="text-[11px] text-zinc-600 font-mono">
              {new Date().toISOString().split("T")[0]} · auto-generated daily
            </p>
          )}
        </div>

        {loading && (
          <p className="text-zinc-500 text-sm">Generating investigation…</p>
        )}

        {error && (
          <div className="bg-red-500/10 border border-red-500/30 rounded-lg p-4 text-sm text-red-300">{error}</div>
        )}

        {dive && (
          <article className="space-y-8">
            <header className="border-b border-white/5 pb-5">
              <h1 className="text-3xl sm:text-4xl font-bold mb-3 leading-tight">{dive.title}</h1>
              <p className="text-base text-zinc-300 leading-relaxed">{dive.summary}</p>
            </header>

            <Section title="Owner background">{dive.ownerBackground}</Section>
            <Section title="Revenue estimate">{dive.revenueEstimate}</Section>
            <Section title="Why now">{dive.whyNow}</Section>

            <section>
              <h2 className="text-xs uppercase tracking-widest text-neon font-semibold mb-3">Rebuild plan</h2>
              <ul className="space-y-2">
                {dive.rebuildPlan.split("\n").filter(Boolean).map((step, i) => (
                  <li key={i} className="flex gap-3 text-sm text-zinc-300 leading-relaxed">
                    <span className="text-neon shrink-0 font-mono">{(i + 1).toString().padStart(2, "0")}</span>
                    <span>{step.replace(/^[-•*]\s*/, "")}</span>
                  </li>
                ))}
              </ul>
            </section>

            <Section title="Outreach &amp; negotiation playbook">{dive.outreachPlan}</Section>

            <section>
              <h2 className="text-xs uppercase tracking-widest text-neon font-semibold mb-3">Red flags · verify before acting</h2>
              <ul className="space-y-1.5">
                {dive.redFlags.map((f, i) => (
                  <li key={i} className="flex gap-2 text-sm text-zinc-400">
                    <span className="text-orange-400 shrink-0">⚠</span>
                    <span>{f}</span>
                  </li>
                ))}
              </ul>
            </section>

            <footer className="pt-6 border-t border-white/5 text-[11px] text-zinc-600 font-mono">
              Generated by AppScout AI · {new Date(dive.generatedAt).toLocaleString()}
            </footer>
          </article>
        )}
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-xs uppercase tracking-widest text-neon font-semibold mb-3">{title}</h2>
      <p className="text-sm text-zinc-300 leading-relaxed whitespace-pre-wrap">{children}</p>
    </section>
  );
}

export default function TodayPage() {
  return (
    <main className="min-h-screen bg-[#050508] text-white">
      <Nav />
      <Suspense fallback={<div className="pt-24 px-6 text-zinc-500 text-sm">Loading…</div>}>
        <TodayContent />
      </Suspense>
      <Footer />
    </main>
  );
}
